source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WXYZoomImage_Example', :exclusive => true do
  pod "WXYZoomImage", :path => "../"
end

target 'WXYZoomImage_Tests', :exclusive => true do
  pod "WXYZoomImage", :path => "../"
end
