language: objective-c
osx_image: xcode7
xcode_project: Example/WXYZoomImage.xcodeproj
xcode_scheme: WXYZoomImage

script:
- set -o pipefail && xcodebuild test -workspace Example/WXYZoomImage.xcworkspace -scheme WXYZoomImage-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
